export type ProfessionPartner = {
    _id?: any;
    id: number;
    name: string;
    location: string;
    skills: string;
    experience: string;
    place: number;
    salary: string;
    rentPrice: string;
    avans: string;
    workwear: string;
    drivePermis: string[];
    langue: string[];
    workHours: string;
    getStart: Date;
    pDocs: string[];
    candidates: string[]; 
    interview: string[];
  };